version: '3'
services:
  web:
    container_name: commonweb
    build: .
    volumes:
      - .:/commonweb:cached
    working_dir: /commonweb
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"