apiVersion: v1
kind: Service
metadata:
  name: commonweb-svc
spec:
  type: NodePort 
  selector:
    app: commonweb
  ports:
  - name: 服务名-sv
    port: 3000
    targetPort: 3000
    nodePort: 30001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: commonweb-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: commonweb
    spec:
      containers:
      - name: commonweb
        image: commonweb
        ports:
        - containerPort: 3000