apiVersion: v1
kind: Service
metadata:
  name: commonweb-svc
spec:
  type: NodePort 
  selector:
    app: commonweb
  ports:
  - name: commonweb-svc
    port: 3000
    targetPort: 3000
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commonweb
  labels:
    app: commonweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commonweb
  template:
    metadata:
      labels:
        app: commonweb
    spec:
      containers:
      - name: commonweb
        image: a112121788/commonweb_pod:20210105091829
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent